import java.util.Properties
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// Generates GoogleOAuthConfig.kt from the `google.web.client.id` / `google.web.client.secret`
// keys in the gitignored local.properties, instead of checking real OAuth credentials into
// this repository. See README "Google Drive setup". Missing keys fall back to placeholder
// strings, matching the previous checked-in file's behavior for a fresh clone.
val googleOAuthConfigDir = layout.buildDirectory.dir("generated/googleOAuthConfig")

val generateGoogleOAuthConfig by tasks.registering {
    val localPropertiesFile = rootProject.file("local.properties")
    val localProperties = Properties()
    if (localPropertiesFile.exists()) {
        localPropertiesFile.inputStream().use { localProperties.load(it) }
    }
    val clientId = localProperties.getProperty("google.web.client.id")
        ?: "REPLACE_WITH_YOUR_WEB_CLIENT_ID.apps.googleusercontent.com"
    val clientSecret = localProperties.getProperty("google.web.client.secret")
        ?: "REPLACE_WITH_YOUR_WEB_CLIENT_SECRET"

    inputs.file(localPropertiesFile).optional(true)
    inputs.property("clientId", clientId)
    inputs.property("clientSecret", clientSecret)
    val outputDir = googleOAuthConfigDir
    outputs.dir(outputDir)

    doLast {
        val packageDir = outputDir.get().asFile.resolve("com/mementostorage/app/auth")
        packageDir.mkdirs()
        packageDir.resolve("GoogleOAuthConfig.kt").writeText(
            """
            |package com.mementostorage.app.auth
            |
            |// Generated by the :composeApp:generateGoogleOAuthConfig Gradle task — do not edit
            |// by hand, and do not paste real credentials anywhere else in this repository.
            |// Fill in google.web.client.id / google.web.client.secret in local.properties
            |// instead (gitignored). See README "Google Drive setup".
            |object GoogleOAuthConfig {
            |    const val webClientId: String = "$clientId"
            |    const val webClientSecret: String = "$clientSecret"
            |}
            |
            """.trimMargin()
        )
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    @OptIn(org.jetbrains.kotlin.gradle.ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("composeApp")
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        commonMain.dependencies {
            implementation(project(":shared"))
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.materialIconsExtended)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            // `shared` depends on these itself via `implementation`, which does not leak
            // transitively — but AppContainer's android/wasmJs actuals both construct a
            // DriveApiClient(createHttpClient(), ...) directly, so this module needs its own
            // visibility into the ktor-client-core types (HttpClient, HttpClientConfig, ...).
            implementation(libs.ktor.client.core)
        }
        getByName("commonMain").kotlin.srcDir(generateGoogleOAuthConfig)
        androidMain.dependencies {
            implementation(compose.uiTooling)
            implementation(libs.androidx.activityCompose)
            implementation(libs.androidx.credentials)
            implementation(libs.androidx.credentials.playServicesAuth)
            implementation(libs.play.services.auth)
            // Photos picked from the device camera/gallery often store pixel data in landscape
            // with an EXIF orientation tag saying how to rotate it for display — BitmapFactory
            // ignores that tag, so without reading it ourselves those photos show sideways.
            implementation(libs.androidx.exifinterface)
        }
        val wasmJsMain by getting {
            dependencies {
                implementation(libs.kotlinx.browser)
                // GoogleAuthClient.wasmJs.kt does its own OAuth token-response JSON decoding.
                implementation(libs.kotlinx.serialization.json)
            }
        }
    }
}

compose.resources {
    // Pinned explicitly so the generated Res accessor's package is known and stable,
    // rather than relying on the plugin's inferred default.
    packageOfResClass = "com.mementostorage.app.generated.resources"
}

android {
    namespace = "com.mementostorage.app"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.mementostorage.app"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "0.1.0"
    }
    packaging {
        resources.excludes.add("/META-INF/{AL2.0,LGPL2.1}")
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}
